### ISSUE TITLE
Can't use hydra-zen anymore. TypeError: Parameters to Protocol[...] must all be type variables. Parameter 2 is ~P

### ISSUE THREAD

**Issue by kiyoon** [mit-ll-responsible-ai/hydra-zen#481]
Hi,

From today, if I make a new conda environment, and install hydra-zen it doesn't work anymore.

```
conda create -n zen-test python=3
conda activate zen-test

pip install hydra-zen

python
>>> import hydra_zen

Traceback (most recent call last):
  File "/home/kiyoon/project/mlproject/tools/notebooks/a.py", line 1, in <module>
    from hydra_zen import instantiate
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/__init__.py", line 5, in <module>
    from ._hydra_overloads import (
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/_hydra_overloads.py", line 31, in <module>
    from .structured_configs._just import just
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/structured_configs/__init__.py", line 4, in <module>
    from ._implementations import builds, hydrated_dataclass, mutable_value
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/structured_configs/_implementations.py", line 50, in <module>
    from hydra_zen.funcs import get_obj
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/funcs.py", line 14, in <module>
    from hydra_zen.structured_configs._utils import (
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/structured_configs/_utils.py", line 51, in <module>
    from hydra_zen.typing import DataclassOptions, ZenConvert
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/typing/__init__.py", line 4, in <module>
    from ._implementations import (
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/hydra_zen/typing/_implementations.py", line 147, in <module>
    class BuildsWithSig(Builds[T], Protocol[T, P]):
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/home/kiyoon/bin/miniconda3/envs/mlproject/lib/python3.10/site-packages/typing_extensions.py", line 672, in __class_getitem__
    raise TypeError(
TypeError: Parameters to Protocol[...] must all be type variables. Parameter 2 is ~P
```

I tried with both Python 3.10 and 3.11. It's weird it just suddenly broke but do you know what may be causing this issue?

Thank you!

**Comment by rsokl** [comment]
This is caused by a bug in the latest version of typing-extensions: https://github.com/python/typing_extensions/issues/181

I will push a patch to pypi that bans this version.

**Comment by kiyoon** [comment]
Thanks a lot!

**Comment by rsokl** [comment]
This should be fixed on pypi now - please confirm when you have a moment

**Comment by kiyoon** [comment]
It works, thank you!
