### ISSUE TITLE
Recursive builds

### ISSUE THREAD

**Issue by alexlatif** [mit-ll-responsible-ai/hydra-zen#699]
When we instantiate recursively in Hydra

```yaml
dnn:
  _target_: __main__.DNN
  input_size: 180
  output_size: 10
  layer_widths:
  - 5
  - 10
  - 5
  block:
    _target_: __main__.BlockEg
    input_size: 160
```

```python
class BlockEg:
    def __init__(self, input_size: int):
        super().__init__()
        self.layer1 = nn.Linear(input_size, 32)


class DNN(nn.Module):
    def __init__(
        self,
        input_size: int,
        output_size: int,
        block: BlockEg = BlockEg(input_size=10),
        layer_widths: tuple[int, ...] = (5, 10, 5),
    ):
        super().__init__()
        self.input_size = input_size
        self.output_size = output_size
        self.layer_widths = layer_widths
        self.block = block
        
d: DNN = instantiate(test_conf.dnn)
```

it would be great to be able to use the `builds` feature in reverse rather than it erroring out. For two reasons:

1. it centralizes the yaml should we prefer to use it

2. it allows for nested blocks to be instantiated in one shot and with defaults initialized

```
❯ pdm run src/hydra_test.py
Traceback (most recent call last):
  File "/Users/alessandrolatif/code/doges/inf_env/ptrain/src/hydra_test.py", line 58, in <module>
    dnn_config = builds(DNN, populate_full_signature=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alessandrolatif/code/doges/inf_env/ptrain/.venv/lib/python3.11/site-packages/hydra_zen/structured_configs/_implementations.py", line 2889, in builds
    _field = cls._sanitized_field(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alessandrolatif/code/doges/inf_env/ptrain/.venv/lib/python3.11/site-packages/hydra_zen/structured_configs/_implementations.py", line 1327, in _sanitized_field
    value = cls._make_hydra_compatible(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alessandrolatif/code/doges/inf_env/ptrain/.venv/lib/python3.11/site-packages/hydra_zen/structured_configs/_implementations.py", line 1271, in _make_hydra_compatible
    raise HydraZenUnsupportedPrimitiveError(err_msg)
hydra_zen.errors.HydraZenUnsupportedPrimitiveError: Building: DNN ..
 The configured value <__main__.BlockEg object at 0x114320d10>, for field `block`, is not supported by Hydra -- serializing or instantiating this config would ultimately result in an error.

Consider using `hydra_zen.builds(<class '__main__.BlockEg'>, ...)` create a config for this particular value.
```

There may be another way I am not yet seeing. Could you please advise what path to pursue in order to achieve this reverse build?

**Comment by alexlatif** [comment]
answered, closed and leaving for more reference:

```python
    dnn_config = builds(DNN, block=block_config, populate_full_signature=True)
```
